CityOfZion/neo-mamba

docs/source/library/network/payloads/transaction.rst
docs/source/library/network/payloads/verification.rst
neo3/network/convenience/nodemanager.py
neo3/network/node.py
neo3/network/payloads/__init__.py
neo3/network/payloads/consensus.py
neo3/network/payloads/transaction.py
neo3/network/payloads/verification.py
requirements.txt
tests/network/convenience/test_nodemanager.py
tests/network/test_node.py
tests/network/test_payloads.py
tests/storage/storagetest.py

- close #9
- improve syncing speed when the local chain is ~in sync with the remote node. Previously the C# nodes broadcasted new blocks faster, now we can lag behind 2-3 seconds. Added a service in node manager to ping remote nodes on a interval to be aware of their new heights faster.

Merge transaction sender and cosigner

---

.circleci/config.yml

Circle-ci is currently setup to require approval on documentation publishing for all branches. This has the effect that either all pull requests will not receive the ✅  because we don't approve the documentation publishing, or the documentation will be approved which will update the live documentation while the documentation changes might only apply to the development version.

Limit documentation publishing step to master only

---

setup.py

wheel building did not include the subpackages under `/neo3/`nor the tests and documentation

Fix wheel inclusions

---

neo3/contracts/interop/contract.py
neo3/contracts/interop/storage.py
neo3/contracts/native/nativecontract.py
neo3/storage/storageitem.py

1) Working with storage states was prone to forgetting to persist the changes back into the storage item if accessed via snapshots. This change takes care of automatically doing this.
2) limit some contract state readings to be readonly (avoids them being reported as deviating from C# during audit as they haven't actually changed)

Simplify working with storage states

---

neo3/core/types/uint.py
tests/core/test_types.py

The UInt types are used a lot around in the NEO system. In just the first 5000 blocks they're created over 86_000 times. The initialization code protects against users initializing them without hex-escaped values, but it is considered too expensive. This changes speeds it up 3x

Change UInt initialization

---

neo3/blockchain.py
neo3/contracts/native/nativecontract.py

For every block produced the validators are read from disk, sorted and persisted. These validators are `ECPoint` objects and they're very expensive to deserialize. By caching the deserialized points we get a 62% speed gain during chain syncing

Fast validators

---

neo3/network/node.py
tests/network/test_node.py

The payload used for requesting headers has changed. We no longer request by hash by but by index

fix requesting headers

---

neo3/contracts/applicationengine.py
neo3/contracts/native/fungible.py

It should be possible to remove your vote on a candidate without voting for a new candidate. This should be doable by specifying `Null` for the `vote_to` argument on the `vote` method. I originally misunderstood the C# code on this part wondering how they could ever have `null` for the vote target. Now I know and this fixes it :)

fix removing vote

---

neo3/network/message.py
neo3/network/node.py
neo3/network/payloads/extensible.py

While the `ExtensiblePayload` already existed, the P2P protocol didn't have a handler for it. This resulted in warnings in the network debug logs.

Add extensible payload handling

---

neo3/api/__init__.py
neo3/api/noderpc.py
neo3/contracts/callflags.py
neo3/contracts/nef.py
requirements.txt
tests/api/test_noderpc.py

This adds the base Neo Node RPC methods. Note that not all method names match 1:1. e.g. `sendrawtransaction` is not mapped to `send_raw_transaction()` but to `send_transaction()`. The latter accepts either a `Transaction` object or a serialised version of a transaction.
I'm looking for some feedback on API usage. It makes sense to me but I'm obviously biased.
Example usage:
```python
from neo3 import api
async def main():
url = "https://mainnet5.neo.coz.io:443"
async with api.NeoRpcClient(url) as client:
try:
print(await client.get_version())
except api.JsonRpcError as e:
print(e)
if __name__ == "__main__":
asyncio.run(main())
```
TODO:
Not convinced yet if its worth the effort (time wise):
- We do not perform any JSON response validation prior to parsing. This could mean we throw …

NeoNode RPC Client

---

neo3/__init__.py
neo3/contracts/applicationengine.py
neo3/contracts/interop/contract.py
tests/contracts/interop/test_contract_interop.py

https://github.com/neo-project/neo/pull/2712 & https://github.com/neo-project/neo-node/pull/862

Fix fee of CreateMultisigAccount 

---

examples/cli/deploy.py
examples/cli/transfer.py
neo3/api/__init__.py
neo3/api/noderpc.py
neo3/contracts/__init__.py
neo3/contracts/vm.py
neo3/core/cryptography/bloomfilter.py
setup.cfg
tests/api/test_noderpc.py
tests/contracts/test_utils.py
tests/core/test_cryptography.py

On successful execution of the deploy and transfer CLI examples one would only get a transaction id. A transaction id does not guarantee success on chain. This PR improves the feedback
* added `-p` option to the scripts to poll the chain for the transaction status with a 20 second timeout (can be specified)
* the deploy script now prints the `contract hash`
* added `poll_tx_status()` helper function

examples, api: improve deploy/transfer feedback

---

neo3/network/payloads/consensus.py
neo3/vm.py

* emit_jump must be able to jump backwards, thus requiring a signed offset
* add support for pushing a native list (this allows i.e. supplying `[something, else]` to the `data` argument of `transfer()` and have it automatically be converted to an `Array` stackitem

vm: add support for pushing native lists in ScriptBuilder, fix emit_jump

---

neo3/wallet/account.py

#183 refactored the project structure and the line in this PR wasn't updated. It did not fail the type check because it was explicitely ignored for other reasons (see the comment above).

wallet: fix sign_tx

---

neo3/contracts/callflags.py
tests/contracts/test_callflags.py

The current parsing can't handle actual flag combinations, just single flags. This solves that

contracts: fix parsing of multiple callflags

---

neo3/network/payloads/block.py
neo3/network/payloads/transaction.py

Back in the full node I optimized the deserialization because it showed to be a bottleneck during syncing. This reverts those optimizations in favour of readability as we're no longer concerned with the highest speed

payloads: revert deserialization optimizations

---

neo3/api/noderpc.py
neo3/api/unwrap.py
neo3/api/wrappers.py

fix #149
This PR is about adding the base code for calling smart contracts conveniently over RPC. From the docstrings of the `wrappers` module
```
Convenience wrappers for calling smart contracts via RPC.
* The most specific wrappers in this module are for NEOs native contracts
* NeoToken, GasToken TODO: add remaining contracts
* One step up are wrappers for contracts following the NEP-17 Token standard (`NEP17Contract`) and NEP-11 NFT standard
(`NEP11Contract`)
* As last resort there is the `GenericContract` which can be used for calling arbitrary functions on arbitrary contracts
Obtaining the results of the functions on the wrapped contracts is done through one of 3 methods
1. test_invoke() - does not persist to chain. Costs no gas.
2. invoke() - does persist to chain. Requires signing …
```

api: add base contract wrappers

---

neo3/api/noderpc.py
tests/api/test_noderpc.py

* Unpacking with `**json` is fast, but breaks as soon as there are more or less keys in the dictionary than expected in the dataclass. It also requires dataclass member names to be identical to the key names in the dictionary. It was nice for quickly developing/prototyping but it's time to improve on this. 
* get_version() didn't work for `neo-go` nodes as they consider `wsport` to be optional (whereas C#/neo-cli does not).

api: improve from_json resilience in RPC response objects & use more pythonic names

---

neo3/api/wrappers.py
neo3/wallet/account.py
neo3/wallet/types.py
neo3/wallet/utils.py

... as argument where account script hash is used
based on https://github.com/CityOfZion/neo-mamba/pull/184#issuecomment-1254627717
some internal discussion and feedback in the PR linked suggests users like also being able to supply an address. 
As regarding the implementation; an alternative proposed by Ricardo is to have `UInt160.from_string`  accept not just the `0xsomehash157a4f61fe446e852575327e` format but also try to parse a NEO address. This sounds nice but has some issues in terms of code structure
* considering the project structure below. The bottom layers may never call upwards
`UInt160`  is part of `CORE` , but `is_valid_address`  is part of `wallet` . `Core` is not allowed to call upwards. This would mean it has to duplicate code
* By duplicating the `is_valid_address` logic …

api, wallet: add NeoAddress type alias, also support NeoAddress

---

neo3/wallet/wallet.py

* `from_json` was broken when using it with `Nep6diskwallet`
* added new convenience constructor to create a wallet from disk

wallet: fix from_json, add from_file

---

neo3/api/helpers/txbuilder.py
neo3/api/wrappers.py

* `Nep17Contract.transfer_multi()` only converted the destination address list if supplied as `NeoAddress`, but did not check if the `source` was supplied as a `NeoAddress` 
* raise exception in TxBuilder on fee calculation error

api: fix transfer_multi for NeoAddress, raise exception in TxBuilder

---

neo3/api/helpers/unwrap.py
neo3/api/noderpc.py
neo3/api/wrappers.py

Instead of wrapping the `ManagementContract` native contract we take a different approach that's more usage friendly
* a static `deploy()` on the base class `GenericContract`
* instance `update` and `destroy` on `GenericContract`
The benefit over wrapping `ManagementContract` is that this approach takes less arguments for the functions. The `ManagementContract` also has only 1 additional useful function we could wrap being `getMinimumDeploymentFee`.

api: add contract deploy, update, destroy

---

neo3/api/noderpc.py

superseded by instance methods `get_transaction_receipt` and `wait_for_transaction_receipt` on `NeoRpcClient`

api: drop poll_tx_status

---

neo3/api/noderpc.py

superseded by instance methods `get_transaction_receipt` and `wait_for_transaction_receipt` on `NeoRpcClient`

api: drop obsolete poll_tx_status

---

docs/source/smart-contracts.md
examples/contract-deploy-update-destroy.py
examples/nep-11-airdrop.py
examples/nep17-airdrop.py
examples/nep17-transfer.py
examples/vote.py
neo3/api/wrappers.py
tests/test_vm.py

The `Config` class (as input to `ChainFacade`) ended up not really having a good purpose anymore in the final design.

api: drop Config class

---

docs/source/smart-contracts.md
examples/contract-deploy-update-destroy.py
examples/nep-11-airdrop.py
examples/nep17-airdrop.py
examples/nep17-transfer.py
examples/vote.py
neo3/api/helpers/signing.py

most parameters used `password` (e.g. everything in `Account` and `Wallet`). This streamlines it across the code base

api, docs, examples: align naming convention of password

---

setup.cfg

NSPCC tested the 3rd party native extensions to work correctly with M1 Mac on Python 3.10. This bumps the versions of those packages. `neo3crypto` and `pybiginteger` versions did not change and just got an M1 wheel added and pushed to pypi. They did test `pybiginteger` just to make sure the build changes produce something valid.

setup: OSX M1 support

---

neo3/network/ipfilter.py
neo3/network/payloads/__init__.py
neo3/network/payloads/address.py
neo3/network/payloads/block.py
neo3/network/payloads/extensible.py
neo3/network/payloads/filter.py
neo3/network/payloads/inventory.py
neo3/network/payloads/ping.py
neo3/network/payloads/transaction.py
neo3/network/payloads/verification.py
neo3/network/payloads/version.py

* enabled `network.payloads` inclusion in the API generator and cleaned up/added doc strings to the classes
* ipfilter docs were taking up too much space in the `neo3.network` overview page due to the included examples. Moved those to inside the `IPFilter` class docstrings to cut down on the overview clutter

docs: include network payloads in API reference, restructure ipfilter docs

---

docs/mkdocs.yml

it needs to be fixed for the API doc reference
example issues

docs: disable dark theme

---

.github/workflows/release-to-pypi.yml
setup.cfg

This fixes 2 issues
1. warnings by PyPi regarding the need to use API token when publishing
2. errors when uploading to PyPi because we had a dependency that used a git commit. Which apparently is not allowed according to https://peps.python.org/pep-0440/#direct-references
> Public index servers SHOULD NOT allow the use of direct references in uploaded distributions. Direct references are intended as a tool for software integrators rather than publishers.

ci: fix pypi publishing

---

.github/workflows/release-to-pypi.yml
setup.cfg

This fixes 3 issues
1. warnings by PyPi regarding the need to use API token when publishing
2. errors when uploading to PyPi because we had a dependency that used a git commit. Which apparently is not allowed according to https://peps.python.org/pep-0440/#direct-references
> Public index servers SHOULD NOT allow the use of direct references in uploaded distributions. Direct references are intended as a tool for software integrators rather than publishers.
3. correct the wheel name

ci: fix pypi publish

---

README.rst

shields.io made a [breaking change](https://github.com/badges/shields/issues/8671) that results in the CI status badge being shown as
this fixes that to

ci: update CI shield badge

---

setup.cfg

For example, we are using such typing annotations everywhere:
https://github.com/CityOfZion/neo-mamba/blob/c3eefed337ea3d6443be981b40b43ab7e9280c0b/neo3/core/cryptography/merkletree.py#L28
where UInt256 is, after all, inherited from an ABCMeta class. 
```python
class UInt256(_UIntBase):
class _UIntBase(serialization.ISerializable):
class ISerializable(abc.ABC):
```
In Python 3.8 and 3.7, typing annotation using an ABCMeta class is not supported. An exception can be raised as:
```
TypeError: 'ABCMeta' object is not subscriptable
```
And Python <= 3.6 does not support such typing annotations from the syntax level.

Maybe we need to specify the supported Python versions in setup.cfg

---

Makefile

fix #250
- removes obsolete Sphinx documentation generation
- use `mkdocs` to build
- add deploy option for manually deploying to s3

setup: update documentation related commands in Makefile

---

neo3/api/wrappers.py
neo3/vm.py

The type of the `data` argument is incorrectly set to assume a list. It can actually be any accepted contract parameter type, whether in a list or not.

api: fix type of data argument

---

.github/workflows/release-to-pypi.yml
.github/workflows/validate-pr-commit.yml

Resolve this
```
Run actions/setup-python@v4.2.0
Resolved as '3.10.11'
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/CityOfZion/neo-mamba/actions/runs/5376319722/jobs/9753387841#step:3:11)-[11](https://github.com/CityOfZion/neo-mamba/actions/runs/5376319722/jobs/9753387841#step:3:12)-github-actions-deprecating-save-state-and-set-output-commands/
Successfully set up CPython …
```

ci: resolve setup-python deprecation warning

---

neo3/network/payloads/verification.py
tests/network/test_issues.py

Mamba could not decode the transaction in block 3367174.
t will fail to find `ConditionScriptHash`  type in this loop https://github.com/CityOfZion/neo-mamba/blob/4ec5a76b1f98381b96cfa78109d48998d821ec7d/neo3/network/payloads/verification.py#L423
because `__subclasses__`  only gets the DIRECT subclasses, not any subclasses down the tree. So that loop will find `ConditionCallByContract`  but not `ConditionScriptHash`  because the tree looks like this
```mermaid
classDiagram
WitnessCondition <|-- ConditionCalledByContract
ConditionCalledByContract <|-- ConditionScriptHash
```
The error it throws is
```
ValueError: Insufficient data - Insufficient data - Deserialization error - unknown witness condition. Type: 24
```
This PR does a recursive search down the inheritance tree to solve it.

network: fix WitnessCondition deserialization

---

neo3/wallet/account.py
neo3/wallet/wallet.py
tests/wallet/test_account.py
tests/wallet/test_wallet.py

A wallet can have multiple accounts that are all encrypted with different passwords. It appears that we only tested loading a wallet from a file where the accounts coincidentally had the same password for all accounts.
This PR changes the signature of `from_file()` and from_json()` to have a list of passwords instead of a single password.

wallet: fix Wallet.from_json/from_file for multiple accounts with passwords

---

neo3/api/helpers/signing.py
neo3/api/helpers/txbuilder.py
neo3/api/wrappers.py

fix #260 (partially)
This PR partially fixes #260 meaning;
- it fixes signing with a `1-of-n` multi-signature account (therefore allowing to e.g. transfer genesis funds from a single consensus node like you'll find in a local development network)
- it does not fix signing with a `m-of-n` multi-signature account where `m >=2`.  I had a look at supporting this and there's quite some additional work to be done around creating multisig unsigned transactions and sharing these around. Considering open tasks in other areas this is postponed until there's an actual request for it.

api: add 1 out n multi-sig signing support for use with ChainFacade

---

neo3/api/noderpc.py

1. `neo-go` nodes return a different error message when a transaction cannot be found. Which breaks the `wait_for_transaction_receipt()`  helper function. 
2. `neo-go` when asking for a transaction that does not exist (e.g. because the block is not yet processed) an error is expected. However, the neo-go nodes do not set the `content-type` of the response to `application/json` like the C# nodes do. This causes a failed content-type check during the conversion to JSON using `aiohttp`. This PR also disables content-type checking in the RPC client.

api: fix wait_for_transaction_receipt for neo-go nodes

---

neo3/wallet/account.py
neo3/wallet/wallet.py

1. scrypt parameters for the `Account` instance where not taken into account when calling `sign()`. Therefore it would always assume the default scrypt parameter. This caused failures in some unittests that used custom scrypt params
2. when importing a multi-signature account the wallet will try to augment that account with the key material of the related accounts so it can be used for signing. This augmentation did not copy the scrypt parameters which could lead to the same issue as `1.`

wallet: fix custom scrypt parameter usage

---

neo3/vm.py
tests/test_vm.py

@luc10921 reported that the following is allowed on the C# side
```
{ "type": "String", "value": ""  }
```
After some investigation is seems like the `ScriptBuilder` simply ignores the value and does not add anything to the stream. It will only push `OpCode.PUSHDATA1` and a length `0` to the byte array. This PR fixes this scenario to also accept empty strings

vm: allow pushing empty strings

---

neo3/api/helpers/unwrap.py
neo3/api/noderpc.py

**The problems**
1. The NEO Virtual Machine has a `Map` type which translates to a `dict` on the Python side. The keys are [restricted](https://github.com/neo-project/neo-vm/blob/ea03316ae34ca4bc7a30fd4b65dad74f1fed7e17/src/Neo.VM/Types/Map.cs#L30) to what they call `PrimitiveType`s being `Boolean` , `Integer` and `ByteString` stack item types (respectively `bool`, `int` and `str` in Python). 
However, it is also possible to push `bytes` using the `PUSHDATA` opcodes which will be converted to a `ByteString` stack item type. Therefore we can no longer assume that when the VM returns a `ByteString` stack item that it is always a `str`. 
2. `int` key types would incorrectly be converted to `str`. 
**The solution**
This PR removes the "ByteString == `str`" assumption and also removes the `int …

api: fix `Map` key processing

---

neo3/api/noderpc.py

There is an issue with Windows that when it has IPv6 enabled and the RpcClient makes a call on a route that is not fully IPv6 it will take a long time to timeout before falling back to IPv4. This caused HUGE delays with boa-test-constructor.
This PR forces the usage of IPv4.

api: disable IPv6 in RpcClient

---

tests/network/convenience/test_various.py

This test seems to be unstable when running in CI on a Windows machine.

ci: disable unstable test

---

neo3/api/noderpc.py
tests/api/test_noderpc.py

Implement support for `FindStorage` as per https://github.com/neo-project/neo-modules/pull/805

api: add `FindStorage` RPC call to `NeoRpcClient`

---

neo3/api/helpers/txbuilder.py

It is not the job of `calculate_system_fee` to say something about the correctness of the script in the transaction. One scenario where the current behaviour is problematic is testing for expected assertion errors with the boa test framework.

api: do not throw on VM FAULT in `calculate_system_fee()`

---

neo3/api/wrappers.py

Other methods like `transfer` accept `NeoAddress` for `source` and `destination`. This streamlines `transfer_friendly` to do the same.

api: accept NeoAddress types in `transfer_friendly()`

---

neo3/api/wrappers.py

The timeout logic in ba2bf07079dc28696203d439333ea098350c5430 turned out to be too tight for Windows. This increases the timeout to solve that.

api: increase receipt timeout value fetching to fix `Windows` loop time inaccuracy

---

neo3/api/helpers/stdlib.py
neo3/vm.py
tests/api/helpers/test_stdlib.py

This utility can be used to deserialize data from smart contract storage that was stored using `StdLib.serialize()`. It can be used with the `FindStorage` RPC method or with  boa-test-constructor's `get_storage()`.

api: add helper to deserialize data that is serialized using the StdLib native contract

---

MANIFEST.in

Ensure consumers of the package can use tools like `mypy` without getting warnings such as
```shell
Skipping analyzing "neo3.wallet": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

setup: make PEP-561 compliant

---

pyproject.toml

Dependabot has [upgraded](https://github.com/nspcc-dev/neofs-testcases/pull/674) aiohttp in the neofs-testcases project, and since we use neo-mamba as a dependency, we would like to fix the version conflict by upgrading aiohttp to the latest version.

Bump aiohttp from 3.8.5 to 3.9.0

---

neo3/api/wrappers.py
neo3/vm.py

NEP-11 defines an optional `tokens` method. the `NEP11Contract` wraps this method and manually unwraps the iterator such that it does not have to rely on RPC servers that have iterator sessions enabled (which many don't). However, that means there's a ~2000 item limit on the return. This helper is part 1 to resolve that limit.
Part 2 will allow defining a start index into the iterator. Combining both allows us to query all items using a while or for loop.

api: add `tokens_count` method to NEP11Contract

---

neo3/api/wrappers.py
neo3/vm.py

There's a 2048 max stack item count limit imposed by the VM which prevent our `unwrap_iterator` helpers from fetching all data from the iterator. By providing a `start_index` we can work around that limit.

vm: add `start_index` to iterator unwrap helpers

---

neo3/vm.py
tests/test_vm.py

Based on feedback from @luc10921 while writing Boa tests. Order should be reversed just like we do for Sequences

vm: fix order when pushing dictionaries with `ScriptBuilder`

---

.github/workflows/release-to-pypi.yml
.github/workflows/validate-pr-commit.yml
pyproject.toml
tests/network/test_node.py

With this PR we will start basing the supported versions on the status as per the official Python [release cycles page](https://devguide.python.org/versions/). We will support the last 2 versions in 'bugfix' mode (a.k.a stable/maintenance). With that Python 3.10 support will be removed as that has been in `security` only mode for some time now.

setup: add Python 3.12 support, drop 3.10

---

neo3/api/noderpc.py
tests/api/test_noderpc.py

When contract state is not found the results in response returns None, because of this interactions using `find_states` result  fail with TypeError (since None cannot be iterated)

api: fix type error when contract state not found

---

neo3/api/helpers/txbuilder.py
neo3/api/helpers/unwrap.py
neo3/api/wrappers.py
neo3/contracts/utils.py

docs: fix various typos in docstrings

---

neo3/api/helpers/txbuilder.py

`set_valid_until_block` would be fixed to ~24 hours (based on an average of 15s per block). This allows for custom values.

api: make valid_until_block configurable in TxBuilder

---

neo3/api/noderpc.py
tests/api/test_noderpc.py

Add new available fields
- hardforks
- RPC iterator enabled
- RPC iterator max results

api: extend `get_version` RPC call with extra fields

---

neo3/api/wrappers.py

- move `total_owned_by` from the `_NEP11Contract` base class to `NEP11NonDivisibleContract`
- deprecate `balance_of` and `balance_of_friendly` in favour of `total_owned_by` and `total_owned_by_friendly` to streamline the function names between `NEP11NonDivisibleContract` and `NEP11DivisibleContract`

api: update NEP-11 wrappers

---

neo3/vm.py

I somehow forgot to add the opcodes for my [own PR](https://github.com/neo-project/neo-vm/pull/491) on the VM.

vm: add `ABORTMSG` & `ASSERTMSG` opcodes

---

neo3/api/wrappers.py

[unclaimedGas](https://github.com/neo-project/neo/blob/994645054aa06a67b1c0ee80618c4f5a5edd1569/src/Neo/SmartContract/Native/NeoToken.cs#L321) calls `CalculateBonus()` which has a [restriction](https://github.com/neo-project/neo/blob/994645054aa06a67b1c0ee80618c4f5a5edd1569/src/Neo/SmartContract/Native/NeoToken.cs#L131) on the end index of `currentIndex+1`. Therefore any extra end index makes no sense anymore and can be removed.

api: deprecate `end` argument in `get_unclaimed_gas()`

---

neo3/api/wrappers.py

`deregister` seems more correct semantically

api: rename `candidate_unregister` to `candidate_deregister`

---

examples/contract-deploy-update-destroy.py
examples/nep-11-airdrop.py
examples/nep17-airdrop.py
examples/nep17-transfer.py
examples/vote.py
neo3/api/wrappers.py

Currently all `test_*` functions of `ChainFacade` directly return the actual result of the called method on the smart contract. Which is very convenient when only using test invokes, but makes it inconvenient when switching between `invoke_` and `test_invoke` because now the return type changed. 
Personally when writing code that ends up persisting to chain (via `invoke`) I start off with `test_invoke` (also with debugging) before swapping it over. By streamlining the return types one does not have to change the result handling code.
Changes in this PR
- all `test_invoke*` now return an `InvokeReceipt` just like regular `invoke*` calls
- `invoke_multi` and `invoke_multi_raw` return `InvokeReceipt[Sequence]` instead of `Sequence`

api, tests: streamline invoke return types

---

neo3/api/helpers/signing.py
neo3/api/wrappers.py

similar to #319 but this time streamline the `signers` argument of `test_invoke*` functions to have the same format as the `invoke_*` functions

api: streamline signer argument of invoke functions

---

neo3/api/wrappers.py

I so often miss this when I'm working with the facade and then decide I want to query something directly over RPC (e.g. `getversion`) and then have to create a separate client with matching host etc.

api: expose `NeoRpcClient` on `ChainFacade`

---

neo3/api/wrappers.py

It turns out the `aiohttp.ClientSession` used internally for the RPC client will instantly try to connect to the RPC host. If such a host is not available it will throw an error. This is problematic for example in `boa-test-constructor` which creates a client before booting the node.

apio: lazy create rpc client

---

examples/contract-deploy-update-destroy.py
examples/nep-11-airdrop.py
examples/nep17-airdrop.py
examples/nep17-transfer.py
examples/vote.py
neo3/api/helpers/signing.py
neo3/api/helpers/txbuilder.py
neo3/api/wrappers.py
neo3/wallet/account.py
neo3/wallet/wallet.py
tests/wallet/test_account.py
tests/wallet/test_wallet.py

We move away from always requiring a password and storing an encrypted private key internally to simply storing the private key. It complicated a lot with arguably minor benefits
Breaking changes:
- renamed `sign_insecure_with_account` -> `sign_with_account`
- also removed `password` argument
- renamed `sign_insecure_with_multisig_account` -> `sign_with_multisig_account`
- also removed `password` argument
- removed `sign_secure_with_account`
- removed `password` argument from `sign`, `sign_tx`, `sign_multisig_tx`, `create_new`, `from_encrypted_key`, `from_private_key`, `from_wif`
- added `password` argument to `to_json` & `from_json`
- removed `password` argument from `account_new`
- added `password` argument to `save`, `to_json`
- removed context manager

wallet: change Account/Wallet password handling

---

neo3/api/wrappers.py

As the title says. Allows overriding the `valid_until_block` property of a transaction when persisting state.

wrappers: allow overriding `valid_until_block` in `ChainFacade` invoke methods
