CityOfZion/neo-mamba

neo3/network/message.py, tests/network/test_message.py
=> Update lz4 with size

docs/source/library/network/message.rst, docs/source/library/network/payloads/block.rst, docs/source/library/network/payloads/filter.rst, neo3/network/convenience/syncmanager.py, neo3/network/message.py, neo3/network/node.py, neo3/network/payloads/__init__.py, neo3/network/payloads/block.py, tests/network/test_message.py, tests/network/test_node.py, tests/network/test_payloads.py
=> Update and rename GetBlockDataPayload

docs/source/library/network/message.rst, docs/source/library/network/payloads/block.rst, neo3/network/payloads/block.py
=> Updates for requesting headers via GetBlocksByIndexPayload

tests/storage/storagetest.py
=> add test for NEO issue #1672

neo3/contracts/abi.py, neo3/contracts/manifest.py, tests/contracts/test_abi.py, tests/contracts/test_manifest.py
=> Update manifest and ABI

neo3/contracts/manifest.py, neo3/core/cryptography/bloomfilter.py, neo3/core/serialization.py, neo3/core/types/uint.py, neo3/network/capabilities.py, neo3/network/message.py, neo3/network/node.py, neo3/network/payloads/address.py, neo3/network/payloads/block.py, neo3/network/payloads/consensus.py, neo3/network/payloads/filter.py, neo3/network/payloads/inventory.py, neo3/network/payloads/transaction.py, neo3/network/payloads/verification.py, neo3/network/payloads/version.py, neo3/network/protocol.py, neo3/storage/contractstate.py, neo3/storage/implementations/leveldb.py, neo3/storage/storageitem.py, neo3/storage/storagekey.py, tests/core/test_serialization.py, tests/core/test_types.py, tests/network/convenience/test_nodemanager.py, tests/network/test_message.py, tests/network/test_node.py, tests/network/test_payloads.py, tests/storage/storagetest.py
=> refactor serializable

.circleci/config.yml, docs/Makefile
=> Add documentation publish step

.circleci/config.yml, README.rst, neo3/contracts/manifest.py, requirements.txt
Switch to a faster JSON library. A quick win good for 3.5% performance
=> Faster JSON

.gitignore, neo3/wallet/__init__.py, neo3/wallet/nep6/__init__.py, neo3/wallet/nep6/nep6diskwallet.py, neo3/wallet/nep6/nep6wallet.py, neo3/wallet/scrypt_parameters.py, neo3/wallet/wallet.py, requirements.txt, tests/wallet/test_account.py, tests/wallet/test_wallet.py
Reopening #69 with the new target.
Also removed mixed codes from other issues that were all together in [simplitech:wallet2](https://github.com/simplitech/neo-mamba/tree/wallet2)
=> Wallet creation using NEP-6

neo3/wallet/account.py
Added ScryptParameters as a parameter instead of just using hardcoded values for N, R, and P.
=> Refactor decrypt and encrypt NEP-2 account

neo3/wallet/account.py, neo3/wallet/wallet.py, tests/wallet/test_wallet.py
implemented the methods to include and remove accounts
closes #63
=> Add and remove accounts in the wallet

neo3/wallet/account.py, neo3/wallet/accountcontract.py, neo3/wallet/nep6/nep6diskwallet.py, neo3/wallet/scrypt_parameters.py, neo3/wallet/wallet.py, tests/wallet/test_wallet.py
Refining file generation using NEP-6 format.
Waiting for #80 and #81 to proceed.
**Related issue**
closes #70
=> Exporting wallet using NEP-6 format

neo3/contracts/native/fungible.py, tests/contracts/native/test_nep17.py
https://github.com/neo-project/neo/pull/2544
=> change initial gas to 52M

neo3/contracts/native/fungible.py
https://github.com/neo-project/neo/pull/2560
=> Revert refuel (neo #2444) 

neo3/contracts/nef.py, tests/contracts/test_nef.py
https://github.com/neo-project/neo/pull/2605
=> update NEF with source field

README.rst, requirements.txt, setup.py
=> Make doc requirements optional

neo3/contracts/applicationengine.py, neo3/contracts/manifest.py, neo3/network/payloads/verification.py, requirements.txt, tests/network/test_witnessrules.py
Audit up to block:
670559 - TestNet 
657576 - MainNet
=> Audit fixes

neo3/contracts/applicationengine.py, neo3/contracts/interop/enumerator.py, neo3/contracts/manifest.py, neo3/storage/cache.py, requirements.txt
Fixes related to MainNet and TestNet audit
=> Audit 2022

neo3/wallet/utils.py
=> Add VM exception message on system fee calculation error

neo3/blockchain.py, neo3/contracts/applicationengine.py, neo3/contracts/native/ledger.py
Covers
https://github.com/neo-project/neo/pull/2628
https://github.com/neo-project/neo/pull/2591
Also fixes `getTransctionHeight` typo
=> Add getTransactionVMState

neo3/contracts/native/crypto.py, tests/core/test_cryptography.py
parity https://github.com/neo-project/neo/pull/2604
=> add murmur32 to cryptolib

neo3/contracts/interop/runtime.py
https://github.com/neo-project/neo/pull/2689
=> Add GetAddressVersion syscall 

neo3/contracts/applicationengine.py, neo3/contracts/interop/storage.py, neo3/contracts/native/management.py, neo3/contracts/native/nativecontract.py
following https://github.com/neo-project/neo/pull/2692
=> Fix storage price

neo3/contracts/native/ledger.py, neo3/network/payloads/verification.py, neo3/network/protocol.py, tests/network/test_payloads.py, tests/network/test_witnessrules.py
https://github.com/neo-project/neo/pull/2685
Correctness of the witness rules and signer changes have been manually tested because mamba has no utility function to transform a StackItem to JSON like C# does. Perhaps something for the future to add
=> Add GetTransactionSigners

neo3/api/noderpc.py
=> Support InteropInterface iterator in RPC execution result

examples/cli/deploy.py, examples/cli/transfer.py, neo3/core/types/uint.py
Light wallet style CLI examples to deploy a contract or transfer NEP-17 tokens
=> CLI deploy and transfer examples

neo3/contracts/native/ledger.py
https://github.com/neo-project/neo/pull/2703
=> add traceable to GetTransactionSigners 

neo3/contracts/applicationengine.py, neo3/contracts/interop/contract.py, neo3/storage/cache.py, requirements.txt, tests/contracts/native/test_nep17.py, tests/network/test_witnessrules.py, tests/storage/storagetest.py
https://github.com/neo-project/neo/pull/2729
https://github.com/neo-project/neo/pull/2755
=> snapshot isolation & dynamic call fix

neo3/contracts/applicationengine.py, neo3/contracts/interop/runtime.py, neo3/contracts/native/designate.py, neo3/contracts/native/fungible.py, neo3/contracts/native/management.py, neo3/contracts/native/oracle.py, tests/contracts/interop/test_runtime.py
https://github.com/neo-project/neo/pull/2747
=> limit notifications

neo3/contracts/native/fungible.py
https://github.com/neo-project/neo/pull/2754 & https://github.com/neo-project/neo/pull/2779
=> Add candidate / voting events 

neo3/contracts/__init__.py, neo3/contracts/contract.py, neo3/contracts/vm.py, neo3/core/__init__.py, tests/contracts/test_contract.py, tests/contracts/test_vm.py, tests/network/test_payloads.py
* adds all interop syscalls
* update ScriptBuilder to accept `ScriptCall` types to be more convenient to work with
=> vm: add interop syscalls

.github/workflows/validate-pr-commit.yml, setup.cfg
don't force unsupported old coverage format
=> ci: fix codecov source

neo3/api/__init__.py, neo3/api/noderpc.py, neo3/api/wrappers.py, tests/api/test_noderpc.py
=> api: add StackItemType enum

.github/workflows/release-to-pypi.yml
* use [build](https://pypi.org/project/build/) frontend
* add dist validation step
=> setup: update release workflow

.github/workflows/release-to-pypi.yml, .github/workflows/validate-pr-commit.yml
Some actions use (soon to be deprecated by github) features.
=> ci: update actions

neo3/contracts/manifest.py, neo3/contracts/nef.py
add convenience `from_file` to `NEF` and `ContractManifest`
=> contract: add from_file to NEF & ContractManifest

neo3/api/noderpc.py
allows for using more argument types without explicit conversion in `NeoRpcClient.invoke_function`
=> api: expand supported types of ContractParam

neo3/api/noderpc.py, setup.cfg
=> api: fix get_next_blockvalidators of NeoRpcClient

neo3/api/noderpc.py
add missing [get_candidates](https://github.com/neo-project/neo-modules/blob/0cd622dffe81de96b01a9b30cc4def4c16e63141/src/RpcServer/RpcServer.Blockchain.cs#L224) call to NeoRpcClient
=> api: add get_candidates

neo3/api/helpers/txbuilder.py, neo3/api/noderpc.py, neo3/contracts/descriptor.py, neo3/contracts/manifest.py, neo3/contracts/nef.py, neo3/core/cryptography/bloomfilter.py, neo3/core/cryptography/merkletree.py, neo3/core/serialization.py, neo3/core/types/uint.py, neo3/network/convenience/syncmanager.py, neo3/network/message.py, neo3/network/node.py, neo3/network/payloads/address.py, neo3/network/payloads/block.py, neo3/network/payloads/consensus.py, neo3/network/payloads/transaction.py, neo3/network/payloads/verification.py, neo3/vm.py, neo3/wallet/account.py, neo3/wallet/wallet.py, setup.cfg, tests/core/test_types.py
* latest mypy disallows implicit optional. 
* also added some other checks that are resolved
=> setup: update mypy

neo3/api/wrappers.py
make mypy happy after the accidental push to master instead of a PR here https://github.com/CityOfZion/neo-mamba/commit/8dbe9101c45008261aa74fc20486b57af9b06b0f
=> api: fix type error

neo3/api/wrappers.py
Invoke `multi` variants to mirror regular `invoke`, `invoke_fast` and `invoke_raw` but this aggregates multiple function calls into a single transaction.
=> api: add invoke_multi_* methods to ChainFacade

README.rst, docs/source/faq.md
... with expected release date
=> docs: add FAQ entry regarding JSON interface, update readme

neo3/contracts/findoptions.py
for parity with https://github.com/neo-project/neo/pull/2819
=> contracts: add Backwards option for Find SYSCALL

.github/workflows/validate-pr-commit.yml, setup.cfg
=> setup: Python 3.11 support

neo3/api/wrappers.py
=> api: remove debug code

neo3/api/wrappers.py
close https://app.clickup.com/t/861mv9848
=> api: expose data argument on transfer_friendly

neo3/__init__.py, setup.cfg
https://github.com/nspcc-dev/neofs-testcases/security/dependabot/10
https://github.com/nspcc-dev/neofs-testcases/security/dependabot/1
=> Update aiohttp to 3.8.5 due to a vulnerability issue

setup.cfg
Did not touch documentation dependencies on purpose.
=> setup: update dependencies

.github/workflows/validate-pr-commit.yml, neo3/api/noderpc.py, neo3/wallet/scrypt_parameters.py, pyproject.toml, tests/network/convenience/test_syncmanager.py, tests/network/test_node.py
=> setup, ci: update Black

neo3/contracts/nef.py
follow https://github.com/neo-project/neo/pull/2939
=> contracts: update NEF script deserialization limit

neo3/api/wrappers.py
`candidate_unregister` called the wrong method.
=> api: fix candidate unregister

neo3/api/wrappers.py
fix incorrect handling of amount.
=> wrappers: fix NEP17Token `transfer_friendly`

neo3/network/capabilities.py
=> network: add Disable compression capability
